version: "3.2"
services:
  rabbitmq:
    build: .
    container_name: 'rabbitmq'
    restart: always
    hostname: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        - 1883:1883
    volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./logs/:/var/log/rabbitmq/
