version: '3.3'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    container_name: 'postgresql'
    hostname: 'postgresql'
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
    ports:
      - '5432:5432'
    volumes: 
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
    driver: local